import type { TripDay } from './trip';

/** Supported destination countries (create/edit trip picker + flag registry). */
export const COUNTRY_OPTIONS = [
  "France",
  "Italy",
  "Spain",
  "United Kingdom",
  "Greece",
  "Egypt",
  "Japan",
  "China",
  "India",
  "Peru",
  "Jordan",
  "Cambodia",
  "Uzbekistan",
  "Mexico",
  "Thailand",
  "Indonesia",
  "The Maldives",
  "The Philippines",
  "Fiji",
  "Mauritius",
  "Bahamas",
  "St. Lucia",
  "Croatia",
  "Seychelles",
  "Portugal",
  "Canada",
  "New Zealand",
  "South Africa",
  "Iceland",
  "Switzerland",
  "Costa Rica",
  "Norway",
  "Tanzania",
  "Nepal",
  "Argentina",
  "Colombia",
  "Kyrgyzstan",
  "Chile",
  "United States",
  "United Arab Emirates",
  "Singapore",
  "South Korea",
  "Australia",
  "Hong Kong",
  "Qatar",
  "Vietnam",
  "Turkey",
  "Morocco",
  "Albania",
  "Saudi Arabia",
  "Germany",
  "Austria",
  "Malaysia",
  "Netherlands",
  "Poland",
  "Hungary",
  "Czechia",
  "Belgium",
  "Ireland",
  "Denmark",
  "Sweden",
  "Finland",
  "Brazil",
  "Taiwan",
  "Bahrain",
  "Romania",
  "Bulgaria",
  "Ukraine",
  "Tunisia",
  "Israel",
  "Oman",
  "Georgia",
  "Armenia",
  "Azerbaijan",
  "Kazakhstan",
  "Mongolia",
  "Sri Lanka",
  "Laos",
  "Myanmar",
  "Dominican Republic",
  "Cuba",
  "Jamaica",
  "Panama",
  "Guatemala",
  "Ecuador",
  "Bolivia",
  "Uruguay",
  "Kenya",
  "Ethiopia",
  "Ghana",
  "Malta",
  "Cyprus",
  "Slovakia",
  "Slovenia",
  "Serbia",
  "Montenegro",
  "Bosnia and Herzegovina",
  "Estonia",
  "Latvia",
  "Lithuania",
  "Andorra",
  "Macau",
  "Barbados",
  "Belize",
  "Honduras",
  "Nicaragua",
  "El Salvador",
  "Madagascar",
  "Botswana",
  "Namibia",
  "Rwanda",
  "Uganda",
  "Zambia",
  "Zimbabwe",
  "Mozambique",
  "Senegal",
  "C\u00f4te d'Ivoire",
  "Kuwait",
  "Lebanon",
  "Iran",
  "Pakistan",
  "Bhutan",
  "Bangladesh",
  "Papua New Guinea",
  "Vanuatu",
  "Samoa",
  "French Polynesia",
  "Luxembourg",
  "Moldova",
  "Belarus",
  "Russia",
  "Algeria",
  "Angola",
  "Cameroon",
  "Paraguay",
  "Venezuela",
  "Trinidad and Tobago",
  "Antigua and Barbuda",
  "Grenada",
  "Dominica",
  "Saint Kitts and Nevis",
  "Saint Vincent and the Grenadines",
  "Guyana",
  "Suriname",
  "Gambia",
  "Malawi",
  "Lesotho",
  "Eswatini",
  "North Macedonia",
  "Kosovo",
] as const;

export type CountryName = (typeof COUNTRY_OPTIONS)[number];

const CANONICAL_BY_KEY = new Map<string, CountryName>(
  COUNTRY_OPTIONS.map((name) => [name.toLowerCase(), name])
);

/** Common aliases / short names → canonical list entry. */
const ALIASES: Record<string, CountryName> = {
  uk: 'United Kingdom',
  'great britain': 'United Kingdom',
  britain: 'United Kingdom',
  england: 'United Kingdom',
  usa: 'United States',
  us: 'United States',
  'u.s.': 'United States',
  'u.s.a.': 'United States',
  america: 'United States',
  uae: 'United Arab Emirates',
  emirates: 'United Arab Emirates',
  maldives: 'The Maldives',
  philippines: 'The Philippines',
  'saint lucia': 'St. Lucia',
  'st lucia': 'St. Lucia',
  korea: 'South Korea',
  'republic of korea': 'South Korea',
  hongkong: 'Hong Kong',
  nz: 'New Zealand',
  'czech republic': 'Czechia',
  czech: 'Czechia',
  holland: 'Netherlands',
  "ivory coast": "Côte d'Ivoire",
  'cote divoire': "Côte d'Ivoire",
  "cote d'ivoire": "Côte d'Ivoire",
  swaziland: 'Eswatini',
  macedonia: 'North Macedonia',
  fyrom: 'North Macedonia',
  burma: 'Myanmar',
  bosnia: 'Bosnia and Herzegovina',
  'bosnia herzegovina': 'Bosnia and Herzegovina',
  'st kitts': 'Saint Kitts and Nevis',
  'st. kitts': 'Saint Kitts and Nevis',
  'st kitts and nevis': 'Saint Kitts and Nevis',
  'st. kitts and nevis': 'Saint Kitts and Nevis',
  'st vincent': 'Saint Vincent and the Grenadines',
  'st. vincent': 'Saint Vincent and the Grenadines',
  'st vincent and the grenadines': 'Saint Vincent and the Grenadines',
  'st. vincent and the grenadines': 'Saint Vincent and the Grenadines',
  trinidad: 'Trinidad and Tobago',
  antigua: 'Antigua and Barbuda',
  png: 'Papua New Guinea',
  tahiti: 'French Polynesia',
  'russian federation': 'Russia',
};

/** Legacy city destinations → country for flag display. */
const CITY_TO_COUNTRY: Record<string, CountryName> = {
  "bangkok": "Thailand",
  "phuket": "Thailand",
  "chiangmai": "Thailand",
  "chiang mai": "Thailand",
  "saigon": "Vietnam",
  "ho chi minh": "Vietnam",
  "ho chi minh city": "Vietnam",
  "nha trang": "Vietnam",
  "hanoi": "Vietnam",
  "danang": "Vietnam",
  "da nang": "Vietnam",
  "tokyo": "Japan",
  "osaka": "Japan",
  "kyoto": "Japan",
  "paris": "France",
  "rome": "Italy",
  "barcelona": "Spain",
  "madrid": "Spain",
  "london": "United Kingdom",
  "athens": "Greece",
  "cairo": "Egypt",
  "beijing": "China",
  "shanghai": "China",
  "delhi": "India",
  "mumbai": "India",
  "lima": "Peru",
  "amman": "Jordan",
  "siem reap": "Cambodia",
  "phnom penh": "Cambodia",
  "tashkent": "Uzbekistan",
  "mexico city": "Mexico",
  "bali": "Indonesia",
  "jakarta": "Indonesia",
  "male": "The Maldives",
  "manila": "The Philippines",
  "suva": "Fiji",
  "port louis": "Mauritius",
  "nassau": "Bahamas",
  "castries": "St. Lucia",
  "dubrovnik": "Croatia",
  "split": "Croatia",
  "victoria": "Seychelles",
  "lisbon": "Portugal",
  "toronto": "Canada",
  "vancouver": "Canada",
  "auckland": "New Zealand",
  "wellington": "New Zealand",
  "cape town": "South Africa",
  "johannesburg": "South Africa",
  "reykjavik": "Iceland",
  "zurich": "Switzerland",
  "geneva": "Switzerland",
  "san jose": "Costa Rica",
  "oslo": "Norway",
  "dar es salaam": "Tanzania",
  "zanzibar": "Tanzania",
  "kathmandu": "Nepal",
  "buenos aires": "Argentina",
  "bogota": "Colombia",
  "bishkek": "Kyrgyzstan",
  "santiago": "Chile",
  "new york": "United States",
  "los angeles": "United States",
  "dubai": "United Arab Emirates",
  "abu dhabi": "United Arab Emirates",
  "singapore": "Singapore",
  "seoul": "South Korea",
  "sydney": "Australia",
  "melbourne": "Australia",
  "hong kong": "Hong Kong",
  "doha": "Qatar",
  "istanbul": "Turkey",
  "marrakech": "Morocco",
  "tirana": "Albania",
  "riyadh": "Saudi Arabia",
  "jeddah": "Saudi Arabia",
  "berlin": "Germany",
  "munich": "Germany",
  "vienna": "Austria",
  "kuala lumpur": "Malaysia",
  "amsterdam": "Netherlands",
  "warsaw": "Poland",
  "budapest": "Hungary",
  "prague": "Czechia",
  "brussels": "Belgium",
  "dublin": "Ireland",
  "copenhagen": "Denmark",
  "stockholm": "Sweden",
  "helsinki": "Finland",
  "rio de janeiro": "Brazil",
  "sao paulo": "Brazil",
  "taipei": "Taiwan",
  "manama": "Bahrain",
  "bucharest": "Romania",
  "sofia": "Bulgaria",
  "kyiv": "Ukraine",
  "kiev": "Ukraine",
  "tunis": "Tunisia",
  "tel aviv": "Israel",
  "jerusalem": "Israel",
  "muscat": "Oman",
  "tbilisi": "Georgia",
  "yerevan": "Armenia",
  "baku": "Azerbaijan",
  "almaty": "Kazakhstan",
  "astana": "Kazakhstan",
  "ulaanbaatar": "Mongolia",
  "colombo": "Sri Lanka",
  "vientiane": "Laos",
  "luang prabang": "Laos",
  "yangon": "Myanmar",
  "punto cana": "Dominican Republic",
  "santo domingo": "Dominican Republic",
  "havana": "Cuba",
  "kingston": "Jamaica",
  "panama city": "Panama",
  "antigua guatemala": "Guatemala",
  "quito": "Ecuador",
  "la paz": "Bolivia",
  "montevideo": "Uruguay",
  "nairobi": "Kenya",
  "addis ababa": "Ethiopia",
  "accra": "Ghana",
  "valletta": "Malta",
  "nicosia": "Cyprus",
  "bratislava": "Slovakia",
  "ljubljana": "Slovenia",
  "belgrade": "Serbia",
  "podgorica": "Montenegro",
  "sarajevo": "Bosnia and Herzegovina",
  "tallinn": "Estonia",
  "riga": "Latvia",
  "vilnius": "Lithuania",
  "andorra la vella": "Andorra",
  "macau": "Macau",
  "bridgetown": "Barbados",
  "belize city": "Belize",
  "tegucigalpa": "Honduras",
  "managua": "Nicaragua",
  "san salvador": "El Salvador",
  "antananarivo": "Madagascar",
  "gaborone": "Botswana",
  "windhoek": "Namibia",
  "kigali": "Rwanda",
  "kampala": "Uganda",
  "lusaka": "Zambia",
  "harare": "Zimbabwe",
  "maputo": "Mozambique",
  "dakar": "Senegal",
  "abidjan": "C\u00f4te d'Ivoire",
  "kuwait city": "Kuwait",
  "beirut": "Lebanon",
  "tehran": "Iran",
  "islamabad": "Pakistan",
  "karachi": "Pakistan",
  "thimphu": "Bhutan",
  "dhaka": "Bangladesh",
  "port moresby": "Papua New Guinea",
  "port vila": "Vanuatu",
  "apia": "Samoa",
  "papeete": "French Polynesia",
  "luxembourg city": "Luxembourg",
  "chisinau": "Moldova",
  "minsk": "Belarus",
  "moscow": "Russia",
  "saint petersburg": "Russia",
  "algiers": "Algeria",
  "luanda": "Angola",
  "yaounde": "Cameroon",
  "asuncion": "Paraguay",
  "caracas": "Venezuela",
  "port of spain": "Trinidad and Tobago",
  "st. john's": "Antigua and Barbuda",
  "saint john's": "Antigua and Barbuda",
  "st george's": "Grenada",
  "roseau": "Dominica",
  "basseterre": "Saint Kitts and Nevis",
  "kingstown": "Saint Vincent and the Grenadines",
  "georgetown": "Guyana",
  "paramaribo": "Suriname",
  "banjul": "Gambia",
  "lilongwe": "Malawi",
  "maseru": "Lesotho",
  "mbabane": "Eswatini",
  "skopje": "North Macedonia",
  "pristina": "Kosovo",
};

export function normalizeCountryName(raw: string): CountryName | null {
  const key = raw.trim().toLowerCase().replace(/\s+/g, ' ');
  if (!key) return null;
  if (ALIASES[key]) return ALIASES[key];
  return CANONICAL_BY_KEY.get(key) ?? null;
}

export function countryFromDestinationLabel(destination: string): CountryName | null {
  const key = destination.trim().toLowerCase().replace(/\s+/g, ' ');
  if (!key) return null;
  return CITY_TO_COUNTRY[key] ?? normalizeCountryName(destination);
}

/** Unique countries in first-seen order from trip days (country field, then city/destination fallback). */
export function uniqueCountriesFromTripDays(days: TripDay[]): CountryName[] {
  const seen = new Set<string>();
  const out: CountryName[] = [];
  for (const day of days) {
    const fromCountry = day.country ? normalizeCountryName(day.country) : null;
    const resolved =
      fromCountry ??
      (day.city ? countryFromDestinationLabel(day.city) : null) ??
      countryFromDestinationLabel(day.destination);
    if (!resolved || seen.has(resolved)) continue;
    seen.add(resolved);
    out.push(resolved);
  }
  return out;
}
